### ISSUE TITLE
.rss file

### ISSUE THREAD

**Issue by filippo-ferrando** [ssddanbrown/rss#6]
Hello! i'm new to rss feeds, i would like to know how to add an rss feed from a .rss file to this container if this app can handle this kind of file or a manner of gather the rss link from that file.
Thanks

**Comment by filippo-ferrando** [comment]
Thanks for the response!
I'm having trouble with unixmen and nixcraft RSS feeds, of you can help me, It would be great!!

**Comment by ssddanbrown** [comment]
@filippo-ferrando So the app `feeds.txt` configuration for those sites would be like so:

```
https://www.unixmen.com/feed/ Unixmen[#328ec3] #news #linux
https://www.cyberciti.com/feed/ nixCraft[#3b5bdb] #news #linux
```

The first URLs on each line are the RSS URLs. The bits afterwards is app-specific configuration to set the name, color and tags, as per [our guidances here](https://github.com/ssddanbrown/rss#feed-configuration).

If a feed button/link is provided on a site, and it downloads an `.xml` file, sometimes you instead need to `Right Click` > `Copy link` for the button/link instead to get the feed url.

Note: From my testing, the nixcraft feed won't load post preview images due to cloudlfare security they have on their site, which blocks requests to check the page from the app.

**Comment by filippo-ferrando** [comment]
Thanks! I'll try right now
